### ISSUE TITLE
Use cglib from Maven instead of copied JAR files

### ISSUE THREAD

**Issue by vogella** [eclipse-windowbuilder/windowbuilder#221]
Project contaíns copies of cglib-nodep-2.2.jar
cglib-nodep-2.2.zip which IIRC @lcaron replaced a while ago.

**Comment by vogella** [comment]
Looks like this library is still needed. I will try to add it to the target platform to source it from there.

**Comment by ptziegler** [comment]
CGLib hasn't been updated in 4 years and according to their GitHub [repository](https://github.com/cglib/cglib), it is no longer being actively maintained.

> IMPORTANT NOTE: cglib is unmaintained and does not work well (or possibly at all?) in newer JDKs, particularly JDK17+. If you need to support newer JDKs, we will accept well-tested well-thought-out patches... but you'll probably have better luck migrating to something like [ByteBuddy](https://bytebuddy.net/).

It seems like other major projects (Spring/JUnit/Eclipse) have moved to ByteBuddy instead. We should probably try to get rid of this dependency, instead of just swapping it out with the latest Maven artifact.

**Comment by ptziegler** [comment]
The embedded CGLib jars have been removed with a6f9368d7ac7d9aa0249d71ef04e9c2d1a5c56f6.

CGLib is no longer maintained, so over the course of several commits, we have slowly migrated WB to ByteBuddy. This dependency is now contributed via the SimRel update site.
