### ISSUE TITLE
WB takes Desktop Background and display it in shell background

### ISSUE THREAD

**Issue by adidiot** [eclipse-windowbuilder/windowbuilder#609]
Hello,

I am using Eclipse 4.19, JDK 21 on Ubuntu 23.04.
WindowBuilder 1.14.0 from https://download.eclipse.org/windowbuilder/updates/milestone/S202310020533/

When I create a simple shell using WB it seems WB takes my Desktop Bakground and display it in design mode 

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/90908346/e218abc4-f150-462c-af46-ee1cc4c9ba4a)

Thanks in advance for your support.

**Comment by ptziegler** [comment]
Yeah... The screen capture on Linux is quite a pain. :/
What I think is happening is that the shell hasn't been rendered yet, by the time we try to capture it. As a result, we capture the area behind it (i.e. your desktop).

We have to do some funky stuff in order to capture shells. Does this problem also happen for other composites/widgets?

**Comment by hippie68** [comment]
Similar issue here with WindowBuilder Current from the Marketplace. Any quick workaround?

**Comment by ptziegler** [comment]
I've cleaned up the snapshot mechanism to partially revert to the old logic (drawing via Cairo directly, rather than SWT), meaning it should behave the same way it used to in older version.

One caveat is that we no longer attempt to capture the window decorations, as they are not part of the shell itself. With X11, this is partially possible but not on Wayland, given the sever limitations when it comes to screen captures.

If you want, you can try it out with the latest milestone build:
https://download.eclipse.org/windowbuilder/updates/milestone/S202311141707

I've closed the bug for now. Feel free to re-open it, if it still shows up with the upcoming release.
