### ISSUE TITLE
GUI not showing

### ISSUE THREAD

**Issue by Tamilarasi-cse** [eclipse-windowbuilder/windowbuilder#711]
suddenly while working with button it throughs a message that window builder unable to show gui,
window bulider encountered unexpected internal error
they could be caused by a window builder bug or by a misconfiguration issue, conflict, partial update,etc
java.lang.Error: Unable to open file /resources/1.8/org/eclipse/wb/swing/FocusTraversalOnArray.java from org.eclipse.wb.swing

**Comment by ptziegler** [comment]
What version of WindowBuilder are you using?

The FocusTraversalOnArray was missing for Java 8 or higher and added with https://github.com/eclipse-windowbuilder/windowbuilder/commit/466ea6c7c5f946448030e2b2619b5d762e5056c1, as part of the 1.14.0 release.

**Comment by ptziegler** [comment]
I'm closing this as "not reproducible". From what I understand, this issue is caused when using an old WindowBuilder version with Java 8 or higher. Given my previous comment, I assume that this is fixed in the recent releases.

Feel free to reopen this issue if this problem continues to exist. But then I need to know which WindowBuilder version, which Eclipse version and which Java version you're using.
