### ISSUE TITLE
Conditional statements are almost always evaluated incorrectly.

### ISSUE THREAD

**Issue by Gamebuster19901** [eclipse-windowbuilder/windowbuilder#754]
### Description:

In the design view, if there is a conditional statement that takes a non-constant expression, it is not evaluated.

Consider the following code:

```java
public class Window {

	private JFrame frame;
	private JTabbedPane pane = new JTabbedPane();

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Window window = new Window();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public Window() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.setBounds(100, 100, 450, 300);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

		setupPane();
	}

	private void setupPane() {
		if(true) {
			pane.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
			pane.setBounds(0, 129, 1000, 511);
			frame.add(pane);
			System.err.println("initial");
		}
		pane.addTab("TEST", null);
		
		for(int i = 0; i < 5; i++) {
			pane.addTab(i + "", null);
		}
		
		return;
	}
	
}
```

### Steps to reproduce:

1. View the above code with the design viewer
2. Note the preview windows shows a JTabbedPane called `pane`.
3. Change`if (true)` in `setupPane()` to `if(false || true)`.
4. Open the design viewer again
5. Note `pane` is missing.

**Comment by ptziegler** [comment]
I looked closer into how the internal model is created and I fear that this is an inevitable consequence of statically parsing the source code.

In short: WindowBuilder doesn't evaluate any expressions. Which is why you have a similar effect when creating composites within e.g. a loop.

One could still try to evaluate an boolean expressions if it doesn't contain unknowns (e.g. the `false || true`) you mentioned, but I think that example just serves as an illustration for something like `if (foo()) {...}`.

A list of all types of supported `if` expressions can be found here:
https://github.com/eclipse-windowbuilder/windowbuilder/blob/823f712ec93699951b372a33d82c35e91a188a94/org.eclipse.wb.core.java/src/org/eclipse/wb/core/eval/ExecutionFlowUtils.java#L467-L488

But in short:

- boolean literals
- `Beans.isDesignTime()`
- lazy initialization (e.g. `if (value == null) {value = ...}`)

Extending this functionality would require invasive changes which far exceeds the amount of time I am able to invest in this project.
