### ISSUE TITLE
Context menu not showing up on UI Elements

### ISSUE THREAD

**Issue by purohitanuj** [eclipse-windowbuilder/windowbuilder#758]
Hi,
In earlier versions of WindowBuilder, I was able to do various tasks on right click on UI Element. For example, I could have placed a button and then right click on it to selection the action of the button, which would open the code editor with that block of new code in place. Another example would be right click on window to assign the "Window Closing" / " Window Closed" event to write a code for that. Now only two options are available.
Please fix it or let me know how I can fix it.
![Context Menu Issue](https://github.com/eclipse-windowbuilder/windowbuilder/assets/166108048/c81efca0-11f6-4ef7-ac28-af505a0e83c0)

See above. Earlier, there were many options were shown if I had right clicked the Button.

![IDE Version](https://github.com/eclipse-windowbuilder/windowbuilder/assets/166108048/2d540acc-d017-4c52-8f5a-b75f9d708c80)
![WindowBuilderInfo](https://github.com/eclipse-windowbuilder/windowbuilder/assets/166108048/2cd4a895-9894-44b0-81c1-231d07edbf2b)

**Comment by purohitanuj** [comment]
This is an example of context menu on button on an older version of Eclipse and WindowBuilder.

![OldMenu](https://github.com/eclipse-windowbuilder/windowbuilder/assets/166108048/57aa819d-1e98-4c59-b461-870bb3d87fb8)

**Comment by ptziegler** [comment]
From a fresh Eclipse IDE 4.31 + WindowBuilder 1.15.0

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/b6109f6b-7c38-427d-8c49-ea329b388bcb)

Perhaps an internal error is thrown somewhere... Can you go to the error view and check if anything is logged there?

**Comment by purohitanuj** [comment]
This is the error which popsup.
I have discovered that if I use direct class provided by the GUI framework, example JDialog, the menu items appear.
However in my project, these classes are extended to new classes and these are drawn correctly but context menu is not displayed.

Example of my project extension:

1.public abstract class MSJInternalFrame extends JInternalFrame
2.public abstract class MSPrintableInternalFrame extends MSJInternalFrame 
3.public abstract class MSPrintableInternalFrameToIMSLayeredPane extends MSPrintableInternalFrame 
4.public class PasswordOptions extends MSPrintableInternalFrameToIMSLayeredPane

This class PasswordOptions has the GUI Element
![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/166108048/7ba06f26-7a13-4573-89e4-fe763dfe2a30)

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/166108048/070eb8dc-5629-4a74-a1f1-cb27f505b58b)

Error which comes in the background
![Screenshot 2024-05-05 084956](https://github.com/eclipse-windowbuilder/windowbuilder/assets/166108048/d39e1864-9479-4d2d-b1f7-2976306c367a)

**Comment by ptziegler** [comment]
The context menu with the classes you have described.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/6f588e36-d507-45de-bce5-232452b43b6b)

Are you by any chance using Java 8? Because this is the only way I can reproduce this problem.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/68ca89bc-6680-40f8-9286-6948c11fe595)

**Comment by purohitanuj** [comment]
Yes. I can confirm that I am using Java8 and on changing to the latest version of Java, I can see the context menus.
But my application runs over embedded system which is compliant for Java8; hence I cannot switch over to newer version.
Any idea if this is going to be fixed or should I revert to older version of Eclipse?

**Comment by ptziegler** [comment]
> Yes. I can confirm that I am using Java8 and on changing to the latest version of Java, I can see the context menus.
But my application runs over embedded system which is compliant for Java8; hence I cannot switch over to newer version.
Any idea if this is going to be fixed or should I revert to older version of Eclipse?

I had a look at it in the past and for some reason, the Eclipse compiler behaves differently when an actual Java 8 JRE is used. Any changes would have to be done there. But given that Java 8 is well beyond the end-of-life (for several years by now), it's unlikely that this will ever be fixed.

If you _need_ to build against Java 8, then my suggestion is to use a modern Java version and instead simply adjust the compiler compliance.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/bed3cbc5-2f2a-41c1-90c1-97d6de3ee427)

**Comment by purohitanuj** [comment]
Thanks. Will check the build on my embedded platform (which is a Linux ARM 32 Hard Float ABI SOC).
Cheers!

**Comment by gss0** [comment]
I also encountered this problem with Java 8.
Even after a clean install of eclipse and the plugin, I did not get the results I was hoping for.

I managed to identify the culprit but I do not know how to solve it. Apparently the problem is due to GridBagLayout.

This bug greatly limits productivity and makes it almost impossible to program easily... please fix it as soon as possible or at least make public directives to mitigate the problem.

Thanks

![Screenshot 2024-09-23 174302](https://github.com/user-attachments/assets/235499dc-3cb1-4882-9a71-316cc319e92a)
![Screenshot 2024-09-23 174319](https://github.com/user-attachments/assets/0143245e-5c54-4de1-b52f-c42e6790cc2d)
![Screenshot 2024-09-23 174331](https://github.com/user-attachments/assets/3950fe9c-998e-428d-a129-8a365631fc59)
![Screenshot 2024-09-23 174434](https://github.com/user-attachments/assets/372c7d63-61eb-4174-928a-6436736b387e)
![Screenshot 2024-09-23 175158](https://github.com/user-attachments/assets/149b086d-f963-4139-b5ac-845a288f67a6)

**Comment by ptziegler** [comment]
See https://github.com/eclipse-windowbuilder/windowbuilder/issues/758#issuecomment-2094801253
