### ISSUE TITLE
Standalone version of WindowBuilder

### ISSUE THREAD

**Issue by kl0ck** [eclipse-windowbuilder/windowbuilder#863]
Is there a standalone version of WindowBuilder? It would be nice to have a packaged version that runs standalone without the need to install a plugin on Eclipse. Many people are using other IDEs like IntelliJ or VS Code, and in these cases it would be useful to have a standalone application to build the GUI.

**Comment by ptziegler** [comment]
The short answer: No.

WindowBuilder makes heavy use of the Eclipse infrastructure, such as the compiler and platform. In order to make it work in other IDEs, they would have to:

- Fully support SWT
- Fully support OSGi
- Fully support e.g. the Eclipse extension points
- Use the JDT parser

Or in other words, this would be a monumental undertaking which I don't see happening for a very long time, if at all.
